[package]
name = "advent_2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent22lib"
path = "src/lib.rs"

[[bin]]
name = "advent22"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.3", features = ["derive"] }
itertools = "0.10.5"
nom = "7.1.3"
